### ISSUE TITLE
Evaluation Statistics (Driving Route, Infraction Score, Completion Score)

### ISSUE THREAD

**Issue by hz3014** [opendilab/InterFuser#22]
Dear Author, I have successfully ran your evaluation code CUDA_VISIBLE_DEVICES=0 ./leaderboard/scripts/run_evaluation.sh

At the end of the process I did not see the Evaluation Statistics (Driving Route, Infraction Score, Completion Score). But I noticed there is sample_result.jason file generated.

I was wondering how do I generate the statistics? Thank you!

**Comment by deepcs233** [comment]
The statistics will saved in `CHECKPOINT_ENDPOINT` that set in run_evaluation.sh. The default file path is sample_result.json and i guess that this file can meet your requirement.
