### ISSUE TITLE
Data generation at 2 fps

### ISSUE THREAD

**Issue by cozeybozey** [opendilab/InterFuser#4]
I saw in the paper that it says you are collecting data at 2 fps and I was wondering what that meant exactly. Do you let the simulation run at higher fps, let's say for example 20 fps and then only collect data for 2 frames each second? Or is everything just running at 2 fps including the simulation itself? I can imagine you would do the former to avoid having many frames that are very similar to each other. What is your opinion on this? If it is the latter, then why would you set it at 2 fps? Is that just the fastest you can get?

**Comment by deepcs233** [comment]
The simulatior run at 20 fps which is same as official leaderboard, and we collect data for 2 frames each second.
