### ISSUE TITLE
Model cannot be created

### ISSUE THREAD

**Issue by jdmdj1999** [opendilab/InterFuser#6]
Thanks for your work. I want to make an evaluation but the model cannot be created. How do I load the model？
`self.net = create_model(self.config.model)`

> RuntimeError: Unknown model (interfuser_baseline_seperate_all)

**Comment by deepcs233** [comment]
Sorry, the code has a small mistake and i have fixed it.

The details:
https://github.com/opendilab/InterFuser/blob/cd0274af6b918019e9c6d76648f80a272474db32/leaderboard/team_code/interfuser_config.py#L25

**Comment by jdmdj1999** [comment]
Thanks a lot

**Comment by Yyb-XJTU** [comment]
Could not set up the required agent:
> Unknown model (interfuser_baseline)
RuntimeError: Unknown model (interfuser_baseline)
(Thanks for your work. I want to make an evaluation but the model cannot be created. How do I load the model？)

**Comment by deepcs233** [comment]
Hi,
Have you installed timm before? You could try uninstall timm and then run the below script:
`cd interfuser
python setup.py develop`

**Comment by Yyb-XJTU** [comment]
Thanks a lot, but i have new problem: (The program seems to be stuck here)

> Setting up the agent
load model: leaderboard/team_code/interfuser.pth.tar
routes_town05_long_05_15_19_36_47
> Loading the world
load
load
load
load
load
load
...

**Comment by Yyb-XJTU** [comment]
okk, thanks!
