### ISSUE TITLE
Having problem setting up the project

### ISSUE THREAD

**Issue by HuakunShen** [opendilab/InterFuser#7]
Thank you for your work.
I am trying to run evaluation locally, but always fail to set up the environment after following instructions in `README.md` on main branch (https://github.com/opendilab/InterFuser#setup).

Also the git url https://gitlab.bj.sensetime.com/shaohao/interfuser.git doesn't exist any more, I am using this github repo.

It seems like problem with `easy_install`

```
EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
```

After running `python setup.py develop`, the `easy_install` command is not found.

I tried many different methods but always have problems setting it up.

Could you update the instruction?

**Comment by deepcs233** [comment]
Sorry, i have fixed this link. You can try pip install setuptools==42 which is an older version.
it's because `easy_install` was deprecate in the latest version setuptools.

Thanks for your feedback.

**Comment by HuakunShen** [comment]
Thanks!

One more typo here https://github.com/opendilab/InterFuser/blob/04b459e3be9b3fb8d4c202763707d59dbce673d0/README.md?plain=1#L38

It should be `cd InterFuser` instead of `cd interfuser`.


To solve the `easy_install` issue, consider using the carla way, rather than installing deprecated `setuptools`
https://github.com/carla-simulator/carla/blob/0c41f167cf1b3f33e23e3be6fb5e1c9552ba5969/PythonAPI/examples/automatic_control.py#L43

**Comment by deepcs233** [comment]
Thanks for your advice, i have fixed the typo.
