### ISSUE TITLE
Werid behavior on town 3 and 4

### ISSUE THREAD

**Issue by JkhwungII** [opendilab/InterFuser#71]
Hi, I tired the model i trained on Town 4 and the model deteted an influx of phantom obstacles like in the video. Is it because train too little epoch or too little data. On town 3 model would be stoped by human behind fence

https://github.com/opendilab/InterFuser/assets/53292322/aa9cf68f-202a-429f-8480-c18f1858752c

https://drive.google.com/file/d/1UbEfer95xR4VS1SzkAWQDLZvVglT6IbT/view?usp=drive_link

**Comment by deepcs233** [comment]
Hi!
It is becasue when when collect the data, we will record all objects near the ego-agent, including the cars **on the bridge**. Then when we train the model, we will let the model to predict the objects near the ego-agent. However, we do not exclude the objects that the ego-agent can not observe directly.
To solve this issue, you can try to collect more data from other towns or delete the related data.

**Comment by JkhwungII** [comment]
Thanks
