### ISSUE TITLE
frame rate of carla is very low

### ISSUE THREAD

**Issue by zygalaxy** [opendilab/InterFuser#90]
When I use your pre-training model, the frame rate of carla0.9.10.1 is very low, which is far less smooth than that shown in your video. What is the problem?

**Comment by deepcs233** [comment]
Hi!

>  the frame rate of carla0.9.10.1 is very low

This is a normal phenomenon. To make the video, we first saved every frame and use the ffmpeg tool to convert them into the video.

**Comment by zygalaxy** [comment]
Thank you very much for your patient answer. I see. I will close the question.
