### ISSUE TITLE
evaluation got wrong

### ISSUE THREAD

**Issue by AlisonZhangyy** [opendilab/InterFuser#92]
Thanks for your code, it's really good, but when I evaluate the model with the pretrained weight, it got error like this, i think maybe I should change the model's name, so can you give me some advice?

![微信图片_20240529105134](https://github.com/opendilab/InterFuser/assets/102003708/f5a1d08a-1cbb-441a-a314-50aa460326c6)

**Comment by StrawHatMario24** [comment]
Hey the issue is marked as close but I am receiving a very similar error, can you let me know how to fix it?
